name: Compile and Release

# Execute this action when merging to the "master" branch
on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]
  #   types: [closed]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_aarch64:
    name: AWS Gravaton Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: PreBuild
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          files: target/aarch64-unknown-linux-gnu/release/rusty-axe
