name: Cross Compile

# Execute this action when merging to the "master" branch
on:
  pull_request:
    branches: [master]
    types: [closed]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_aarch64:
    name: AWS Gravaton Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu
